# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Iris en Marijn"
description: > # this means to ignore newlines until "email:"
   Onze website

email: marijn.vanderzee@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/irisenmarijn.jpg"

name: 'Iris Lindner | Marijn van der Zee'
author: 'Marijn van der Zee'
author_image: "/assets/images/marijn.jpg"

paginate:	5

url: "http://www.irisenmarijn.nl" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@marijnvanderzee'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/marijnvanderzee
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/serra/www.irisenmarijn.nl
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
